channels:
- conda-forge
dependencies:
- hatchling =1.28.0
- hatch-vcs =0.5.0
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- python >=3.11, <3.14
- numpy =2.4.0
- networkx =3.6.1
